package com.leonjr.ldo.validation.helper;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.leonjr.ldo.parsing.etl.interfaces.LLMValidation;
import com.leonjr.ldo.parsing.llm.AiHelper;
import com.leonjr.ldo.validation.models.LLMValidationResult;

import dev.langchain4j.data.message.UserMessage;
import dev.langchain4j.model.chat.request.ChatRequest;
import dev.langchain4j.model.chat.request.ResponseFormat;
import dev.langchain4j.model.chat.request.ResponseFormatType;

public class LLMValidationHelper {

    /**
     * Performs semantic validation of an LLM's generated response against an
     * original context and query.
     * This method uses the AiServices approach from Langchain4j.
     *
     * @param originalContext   The original text/document.
     * @param generatedResponse The response generated by another LLM.
     * @param originalQuery     The original query or task description given to the
     *                          first LLM.
     * @return An LLMValidationResult object containing the validation
     *         metrics.
     * @throws JsonProcessingException if there's an issue processing JSON.
     */
    public static LLMValidationResult performLLMValidationWithAiService(
            String originalContext,
            String generatedResponse,
            String originalQuery) throws JsonProcessingException, Exception {
        LLMValidation etlValidationAgent = AiHelper.buildNewValidator();
        UserMessage userMessage = UserMessage.from("original_context" + originalContext + "\ngenerated_response" +
                generatedResponse + "\noriginal_query" + originalQuery);
        ResponseFormat jsonFormat = ResponseFormat.builder()
                .type(ResponseFormatType.JSON)
                .build();
        ChatRequest chatRequest = ChatRequest.builder()
                .responseFormat(jsonFormat)
                .messages(userMessage)
                .build();
        return etlValidationAgent.validate(chatRequest);
    }
}
