package com.leonjr.ldo.validation;

import com.fasterxml.jackson.databind.JsonNode;
import com.leonjr.ldo.database.models.TableDescription;
import com.leonjr.ldo.validation.helper.LLMValidationHelper;
import com.leonjr.ldo.validation.helper.LocalHelper;
import com.leonjr.ldo.validation.models.LLMValidationResult;
import com.leonjr.ldo.validation.models.LocalSimpleValidationResult;
import com.leonjr.ldo.validation.models.LocalValidationResult;

public class ETLValidation {

        /**
         * Validates the output generated by a Large Language Model (LLM) against the
         * original context and query.
         * 
         * This method performs comprehensive validation of LLM-generated responses by
         * comparing them with
         * the original context and query to ensure accuracy, relevance, and
         * consistency.
         * 
         * @param originalContext   the original context or input data that was provided
         *                          to the LLM
         * @param generatedResponse the response or output generated by the LLM
         * @param originalQuery     the original query or prompt that was sent to the
         *                          LLM
         * @return LLMValidationResult containing the validation results and metrics
         * @throws Exception if an error occurs during the validation process
         */
        public static LLMValidationResult validateLLMOutput(String originalContext,
                        String generatedResponse, String originalQuery) throws Exception {
                return LLMValidationHelper.performLLMValidationWithAiService(originalContext, generatedResponse,
                                originalQuery);
        }

        /**
         * Validate the parsed JSON against the target JSON and the schema. This is
         * useful for checking the parsed JSON against the target testing JSON and the
         * schema.
         * 
         * @param targetJson       The target JSON to be compared with.
         * @param parsedJson       The parsed JSON to be validated.
         * @param tableDescription The table description containing the schema.
         * @return A LocalValidationResult object containing the validation results.
         */
        public static LocalValidationResult validateParsingWithTestJson(JsonNode targetJson, JsonNode parsedJson,
                        TableDescription tableDescription) throws Exception {
                LocalValidationResult result = new LocalValidationResult();
                var missingMandatoryFields = LocalHelper.checkMandatoryFields(parsedJson,
                                tableDescription.getFullJsonSchemaFromToJson().get("columns"));
                var dataTypeErrors = LocalHelper.checkDataTypes(parsedJson,
                                tableDescription.getFullJsonSchemaFromToJson().get("columns"));
                var conformityAndUnknownRate = LocalHelper.conformityAndUnknownRate(parsedJson,
                                tableDescription.getFullJsonSchemaFromToJson().get("columns"));
                var precisionRecallF1 = LocalHelper.precisionRecallF1(targetJson, parsedJson);
                var jaccardSimilarity = LocalHelper.jaccardSimilarity(targetJson, parsedJson);
                result.setMissingMandatoryFields(missingMandatoryFields);
                result.setDataTypeErrors(dataTypeErrors);
                result.setConformityAndUnknownRate(conformityAndUnknownRate);
                result.setPrecisionRecallF1(precisionRecallF1);
                result.setJaccardSimilarity(jaccardSimilarity);
                return result;
        }

        /**
         * * Validate the parsed JSON without comparing it to the target JSON. This is
         * useful for checking the parsed JSON against the schema and when does not have
         * a target testing JSON.
         * 
         * @param parsedJson       The parsed JSON to be validated.
         * @param tableDescription The table description containing the schema.
         * @return A LocalValidationResult object containing the validation results.
         */
        public static LocalSimpleValidationResult validateParsingLocally(JsonNode parsedJson,
                        TableDescription tableDescription) throws Exception {
                LocalSimpleValidationResult result = new LocalSimpleValidationResult();
                var missingMandatoryFields = LocalHelper.checkMandatoryFields(parsedJson,
                                tableDescription.getFullJsonSchemaFromToJson().get("columns"));
                var dataTypeErrors = LocalHelper.checkDataTypes(parsedJson,
                                tableDescription.getFullJsonSchemaFromToJson().get("columns"));
                var conformityAndUnknownRate = LocalHelper.conformityAndUnknownRate(parsedJson,
                                tableDescription.getFullJsonSchemaFromToJson().get("columns"));
                result.setMissingMandatoryFields(missingMandatoryFields);
                result.setDataTypeErrors(dataTypeErrors);
                result.setConformityAndUnknownRate(conformityAndUnknownRate);
                return result;
        }
}
